mysql:
  rootPassword: "root"
  database: "practice_board"
  user: "user"
  password: "userpassword"
  rootHost: "%"

persistence:
  size: 1Gi
  storageClass: manual

nodeSelector:
  nodegroup-type: "backend-workloads"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "${aws_security_group.PRI-SG.id}"
