persistence:
  enabled: true
  size: 1Gi
  storageClass: manual
  accessMode: ReadWriteOnce
  hostPath: /mnt/data/tomcat

tomcatImage:
  repository: tomcat
  tag: latest

mysql:
  dbHost: mysql-db
  dbPort: 3306
  dbName: tomcatdb
  dbUser: user
  dbPassword: password
