apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginxweb.fullname" . }}-config
  labels:
    {{- include "nginxweb.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{ .Values.nginx.config.nginxConf | nindent 4 }}
  default.conf: |
    {{ .Values.nginx.config.defaultConf | nindent 4 }}
