apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginxweb.fullname" . }}
  labels:
    {{- include "nginxweb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nginxweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginxweb.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-persistent-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config-volume
          configMap:
            name: {{ include "nginxweb.fullname" . }}-config
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "nginxweb.fullname" . }}-pvc
