apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nginxweb.fullname" . }}-pv
  labels:
    {{- include "nginxweb.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  hostPath:
    path: "/mnt/nginx-data"
