apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatwas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatwas
  template:
    metadata:
      labels:
        app: tomcatwas
    spec:
      nodeSelector:
        nodegroup-type: "backend-workloads"
      containers:
        - name: tomcatwas
          image: {{ .Values.tomcatImage.repository }}:{{ .Values.tomcatImage.tag }}
          volumeMounts:
            - name: website-content
              mountPath: /usr/local/tomcat/webapps/index.html
              subPath: index.html
            - name: mysql-content
              mountPath: /usr/local/tomcat/webapps/mysql.jsp
              subPath: mysql.jsp
            - name: main-content
              mountPath: /usr/local/tomcat/webapps/main.html
              subPath: main.html
      volumes:
        - name: website-content
          configMap:
            name: init-tomcatwas-config
            items:
              - key: "index.html"
                path: "index.html"
        - name: mysql-content
          configMap:
            name: init-tomcatwas-config
            items:
              - key: "mysql.jsp"
                path: "mysql.jsp"
        - name: main-content
          configMap:
            name: init-tomcatwas-config
            items:
              - key: "main.html"
                path: "main.html"
